# Generated by Django 3.0.3 on 2020-02-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thornament', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tournaments',
            new_name='Tournament',
        ),
    ]
