# Generated by Django 3.0.3 on 2020-02-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thornament', '0002_auto_20200225_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('Single Elemenation', 'Single Elemenation'), ('Double Elemenation', 'Double Elemenation'), ('Round Robin', 'Round Robin')], max_length=200, null=True),
        ),
    ]
