# Generated by Django 3.0.3 on 2020-03-01 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thornament', '0005_auto_20200228_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thornament.Tournament')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thornament.League')),
            ],
        ),
    ]
