# Generated by Django 3.0.3 on 2020-03-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thornament', '0006_leagueparticipant_tournamentparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueparticipant',
            name='Participant_point',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='leagueparticipant',
            name='participant_loss',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='leagueparticipant',
            name='participant_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='leagueparticipant',
            name='participant_ot',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='leagueparticipant',
            name='participant_win',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='Participant_point',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='participant_loss',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='participant_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='participant_ot',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='participant_win',
            field=models.IntegerField(null=True),
        ),
    ]
